# Generated by Django 3.2.8 on 2021-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsImportationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_connection_good', models.BooleanField(default=True, verbose_name='connection')),
                ('last_time_cron_ran', models.DateTimeField(auto_now_add=True, verbose_name='last time cron ran')),
                ('time_online', models.TimeField(verbose_name='time online')),
                ('memory_usage', models.CharField(max_length=50, verbose_name='memory usage')),
            ],
            options={
                'verbose_name': 'Product Importation History',
                'verbose_name_plural': 'Products Importation History',
            },
        ),
    ]
