# Generated by Django 3.2.8 on 2021-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsimportationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimportationhistory',
            name='time_online',
            field=models.CharField(max_length=50, verbose_name='time online'),
        ),
    ]
