# Generated by Django 3.2.8 on 2021-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsimportationapp', '0002_alter_productsimportationhistory_time_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimportationhistory',
            name='memory_usage',
            field=models.CharField(max_length=200, verbose_name='memory usage'),
        ),
    ]
